# Generated by Django 4.1.2 on 2022-12-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('rg_password', models.CharField(max_length=100)),
                ('rg_mobile', models.CharField(max_length=100)),
                ('rg_age', models.CharField(max_length=100)),
                ('rg_gender', models.CharField(max_length=100)),
            ],
        ),
    ]
