# Generated by Django 4.1.5 on 2023-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin_name', models.CharField(max_length=40)),
                ('admin_email', models.CharField(max_length=40)),
                ('admin_mobile', models.CharField(max_length=40)),
                ('admin_password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pd_name', models.CharField(max_length=40)),
                ('pd_image', models.ImageField(upload_to='app/static/images')),
                ('pd_category', models.CharField(max_length=40)),
                ('pd_sub_category', models.CharField(max_length=40)),
                ('pd_price', models.CharField(max_length=40)),
                ('pd_description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('sc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sc_ct_name', models.CharField(max_length=40)),
                ('sc_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
