# Generated by Django 4.1.5 on 2023-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_category_product_sub_category_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_us_id', models.CharField(max_length=40)),
                ('ct_pd_name', models.CharField(max_length=40)),
                ('ct_pd_image', models.ImageField(upload_to='app/static/images')),
                ('ct_quantity', models.CharField(max_length=40)),
                ('ct_price', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('or_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('or_us_id', models.CharField(max_length=40)),
                ('or_amount', models.CharField(max_length=40)),
                ('or_status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_products',
            fields=[
                ('pp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pp_or_id', models.CharField(max_length=40)),
                ('pp_name', models.CharField(max_length=40)),
                ('pp_image', models.ImageField(upload_to='app/static/images')),
                ('pp_price', models.CharField(max_length=40)),
                ('pp_quantity', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('us_name', models.CharField(max_length=40)),
                ('us_email', models.CharField(max_length=40)),
                ('us_mobile', models.CharField(max_length=40)),
                ('us_password', models.CharField(max_length=40)),
                ('us_address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('wl_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('wl_us_id', models.CharField(max_length=40)),
                ('wl_pd_name', models.CharField(max_length=40)),
                ('wl_pd_image', models.ImageField(upload_to='app/static/images')),
                ('wl_qty', models.CharField(max_length=40)),
                ('wl_price', models.CharField(max_length=40)),
            ],
        ),
    ]
